let ts = 'resources/images/'
let imageFilenames = [
  ts + 'IMG001.jpg',
  ts + 'IMG002.jpg',
  ts + 'IMG003.jpg',
  ts + 'IMG004.jpg',
  ts + 'IMG005.jpg',
  ts + 'IMG006.jpg',
  ts + 'IMG007.jpg',
  ts + 'IMG008.jpg',
  ts + 'IMG009.jpg',
  ts + 'IMG010.jpg',
  ts + 'IMG011.jpg',
  ts + 'IMG012.jpg',
  ts + 'IMG013.jpg',
  ts + 'IMG014.jpg',
  ts + 'IMG015.jpg',
  ts + 'IMG017.jpg',
  ts + 'IMG018.jpg',
  ts + 'IMG019.jpg',
  ts + 'IMG020.jpg',
  ts + 'IMG021.jpg',
  ts + 'IMG022.jpg',
  ts + 'IMG023.jpg',
  ts + 'IMG024.jpg',
  ts + 'IMG025.jpg',
  ts + 'IMG026.jpg',
  ts + 'IMG027.jpg',
  ts + 'IMG028.jpg',
  ts + 'IMG029.jpg',
  ts + 'IMG030.jpg',
  ts + 'IMG031.jpg',
  ts + 'IMG032.jpg',
  ts + 'IMG033.jpg',
  ts + 'IMG034.jpg',
  ts + 'IMG035.jpg',
  ts + 'IMG036.jpg',
  ts + 'IMG037.jpg',
  ts + 'IMG038.jpg',
  ts + 'IMG039.jpg',
  ts + 'IMG040.jpg',
  ts + 'IMG041.jpg',
  ts + 'IMG042.jpg',
  ts + 'IMG043.jpg',
  ts + 'IMG044.jpg',
  ts + 'IMG045.jpg',
  ts + 'IMG046.jpg',
  ts + 'IMG047.jpg',
  ts + 'IMG048.jpg',
  ts + 'IMG049.jpg',
  ts + 'IMG050.jpg',
  ts + 'IMG051.jpg',
  ts + 'IMG052.jpg',
  ts + 'IMG053.jpg',
  ts + 'IMG054.jpg',
  ts + 'IMG055.jpg',
  ts + 'IMG056.jpg',
  ts + 'IMG057.jpg',
  ts + 'IMG058.jpg',
  ts + 'IMG059.jpg',
  ts + 'IMG060.jpg',
  ts + 'IMG061.jpg',
  ts + 'IMG062.jpg',
  ts + 'IMG063.jpg',
  ts + 'IMG064.jpg',
  ts + 'IMG065.jpg',
  ts + 'IMG066.jpg',
  ts + 'IMG067.jpg',
  ts + 'IMG068.jpg',
  ts + 'IMG069.jpg',
  ts + 'IMG070.jpg',
  ts + 'IMG071.jpg',
  ts + 'IMG073.jpg',
  ts + 'IMG077.jpg',
  ts + 'IMG082.jpg',
  ts + 'IMG092.jpg',
  ts + 'IMG093.jpg',
  ts + 'IMG094.jpg',
  ts + 'IMG095.jpg',
  ts + 'IMG096.jpg',
  ts + 'IMG097.jpg',
  ts + 'IMG098.jpg',
  ts + 'IMG101.jpg',
  ts + 'IMG102.jpg',
  ts + 'IMG103.jpg',
  ts + 'IMG105.jpg',
  ts + 'IMG107.jpg',
  ts + 'IMG108.jpg',
  ts + 'IMG109.jpg',
  ts + 'IMG110.jpg',
  ts + 'IMG111.jpg',
  ts + 'IMG113.jpg',
  ts + 'IMG114.jpg',
  ts + 'IMG116.jpg',
  ts + 'IMG117.jpg',
  ts + 'IMG118.jpg',
  ts + 'IMG119.jpg',
  ts + 'IMG121.jpg',
  ts + 'IMG123.jpg',
  ts + 'IMG124.jpg',
  ts + 'IMG125.jpg',
  ts + 'IMG127.jpg',
  ts + 'IMG129.jpg',
  ts + 'IMG130.jpg',
  ts + 'IMG131.jpg',
  ts + 'IMG132.jpg',
  ts + 'IMG133.jpg',
  ts + 'IMG134.jpg',
  ts + 'IMG137.jpg',
  ts + 'IMG140.jpg',
  ts + 'IMG143.jpg',
  ts + 'IMG145.jpg',
  ts + 'IMG146.jpg',
  ts + 'IMG147.jpg',
  ts + 'IMG148.jpg',
  ts + 'IMG150.jpg',
  ts + 'IMG151.jpg',
  ts + 'IMG152.jpg',
  ts + 'IMG153.jpg',
  ts + 'IMG154.jpg',
  ts + 'IMG155.jpg',
  ts + 'IMG156.jpg',
  ts + 'IMG157.jpg',
  ts + 'IMG158.jpg',
  ts + 'IMG159.jpg',
  ts + 'IMG160.jpg',
  ts + 'IMG165.jpg',
  ts + 'IMG167.jpg',
  ts + 'IMG168.jpg',
  ts + 'IMG171.jpg',
  ts + 'IMG181.jpg',
  ts + 'IMG182.jpg',
  ts + 'IMG184.jpg',
  ts + 'IMG185.jpg',
  ts + 'IMG187.jpg',
  ts + 'IMG190.jpg',
  ts + 'IMG191.jpg',
  ts + 'IMG192.jpg',
  ts + 'IMG193.jpg',
  ts + 'IMG194.jpg',
  ts + 'IMG196.jpg',
  ts + 'IMG199.jpg',
  ts + 'IMG201.jpg',
  ts + 'IMG203.jpg',
  ts + 'IMG204.jpg',
  ts + 'IMG205.jpg',
  ts + 'IMG206.jpg',
  ts + 'IMG207.jpg',
  ts + 'IMG208.jpg',
  ts + 'IMG209.jpg',
  ts + 'IMG210.jpg',
  ts + 'IMG211.jpg',
  ts + 'IMG212.jpg',
  ts + 'IMG213.jpg',
  ts + 'IMG214.jpg',
  ts + 'IMG215.jpg',
  ts + 'IMG216.jpg',
  ts + 'IMG217.jpg',
  ts + 'IMG218.jpg',
  ts + 'IMG219.jpg',
  ts + 'IMG220.jpg',
  ts + 'IMG221.jpg'
]

let picStimuli = [
  { stimulus: ts + 'IMG001.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG002.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG003.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG004.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG005.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG006.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG007.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG008.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG009.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG010.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG011.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG012.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG013.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG014.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG015.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG017.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG018.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG019.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG020.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG021.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG022.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG023.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG024.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG025.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG026.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG027.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG028.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG029.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG030.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG031.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG032.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG033.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG034.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG035.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG036.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG037.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG038.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG039.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG040.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG041.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG042.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG043.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG044.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG045.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG046.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG047.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG048.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG049.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG050.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG051.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG052.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG053.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG054.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG055.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG056.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG057.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG058.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG059.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG060.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG061.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG062.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG063.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG064.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG065.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG066.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG067.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG068.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG069.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG070.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG071.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG073.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG077.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG082.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG092.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG093.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG094.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG095.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG096.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG097.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG098.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG101.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG102.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG103.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG105.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG107.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG108.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG109.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG110.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG111.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG113.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG114.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG116.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG117.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG118.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG119.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG121.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG123.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG124.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG125.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG127.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG129.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG130.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG131.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG132.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG133.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG134.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG137.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG140.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG143.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG145.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG146.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG147.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG148.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG150.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG151.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG152.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG153.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG154.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG155.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG156.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG157.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG158.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG159.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG160.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG165.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG167.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG168.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG171.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG181.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG182.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG184.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG185.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG187.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG190.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG191.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG192.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG193.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG194.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG196.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG199.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG201.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG203.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG204.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG205.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG206.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG207.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG208.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG209.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG210.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG211.jpg', data: { pic_type: 'Positive' } },
  { stimulus: ts + 'IMG212.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG213.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG214.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG215.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG216.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG217.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG218.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG219.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG220.jpg', data: { pic_type: 'Neutral' } },
  { stimulus: ts + 'IMG221.jpg', data: { pic_type: 'Neutral' } }
]

const positiveImages = picStimuli
  .filter(
    stimulus =>
      function (stimulus) {
        return stimulus.data.pic_type === 'Positive'
      }
  )
  .map(pic => pic.stimulus)

const neutralImages = picStimuli
  .filter(
    stimulus =>
      function (stimulus) {
        return stimulus.data.pic_type === 'Neutral'
      }
  )
  .map(pic => pic.stimulus)

const fixationCross = ts + 'fixationCross.png'

let previewNegativeFileNames = positiveImages.slice(3)
let previewPositiveFileNames = neutralImages.slice(3)

export {
  fixationCross,
  imageFilenames,
  picStimuli,
  positiveImages as positiveImageFilePaths,
  neutralImages as neutralImageFilePaths,
  previewNegativeFileNames,
  previewPositiveFileNames,
}
